// <auto-generated />
using ISTAPRO12.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ISTAPRO12.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190430172716_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ISTAPRO12.Models.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloseDate");

                    b.Property<string>("CustEmail")
                        .IsRequired();

                    b.Property<int>("CustID");

                    b.Property<string>("CustName")
                        .IsRequired();

                    b.Property<int>("EmpID");

                    b.Property<string>("Issue")
                        .IsRequired();

                    b.Property<string>("OpenDate");

                    b.Property<string>("Platform")
                        .IsRequired();

                    b.Property<string>("Resolution");

                    b.Property<string>("SubmitDate");

                    b.Property<string>("Summary")
                        .IsRequired();

                    b.HasKey("TicketID");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
